apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: microservices-demo

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - api-gateway/
  - user-service/
  - order-service/
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: microservices-demo
